### ISSUE TITLE
Expose version in `User-Agent` header when querying the AMO API

### ISSUE THREAD

**Issue by willdurand** [mozilla/sign-addon#1149]
Similar to https://github.com/mozilla/web-ext/issues/2538 but we'll also need to pass the`web-ext` version somehow (and default to `n/a` or something like that).

**Comment by eviljeff** [comment]
https://github.com/mozilla/web-ext/pull/2540 sets the `User-Agent` header for `web-ext` for requests via `sign-addon` (there's already support for passing on [arbitrary request config](https://github.com/mozilla/sign-addon/blob/master/src/index.js#L60)) so if we need to make any changes in `sign-addon` it would only be to send a default header when `sign-addon` is used independently of `web-ext` (and the user doesn't themselves set the `User-Agent` header.

**Comment by willdurand** [comment]
@eviljeff we can probably wontfix this issue then?

**Comment by eviljeff** [comment]
Given the maintenance status of `sign-addon`, yeah, probably.
