### ISSUE TITLE
Add option to pipe signed files to a buffer

### ISSUE THREAD

**Issue by kumar303** [mozilla/sign-addon#15]
When signed files are fetched from the AMO web service, they are downloaded to some directory. It might be nice to pipe it to a buffer instead and offer it as a parameter on the returned `result` object. This is what [zip-dir does by default](https://github.com/jsantell/node-zip-dir#example), for example.

**Comment by hitesh4** [comment]
I had been trying to work on this issue but i m not able sign the add-on(xpi file) with jpm sign, but always show an error. I am attaching the screenshot of the command window.
![screenshot from 2016-10-15 08-48-17](https://cloud.githubusercontent.com/assets/12246432/19407090/c4aaec42-92b4-11e6-9fed-a3d2cbc4460d.png)

**Comment by kumar303** [comment]
Do you need to use a proxy? If so, are you able to use [web-ext](https://github.com/mozilla/web-ext) for testing instead? That has better proxy support. Here are some examples to use: https://github.com/mdn/webextensions-examples/

**Comment by hitesh4** [comment]
Yeah, i need to use proxy for connecting, it always says Dulicate add-on id, even i tried creating a new add-on and tried signing it. Could you help me with what am i doing wrong.

**Comment by kumar303** [comment]
ok, it sounds like you resolved the proxy error, good. As for the 'Duplicate add-on id' error, did you try changing the ID in `manifest.json`? If that still gives you an error, try changing the version number.
