### ISSUE TITLE
Allow signing versions of an add-on in the 'unlisted' channel

### ISSUE THREAD

**Issue by mi-g** [mozilla/sign-addon#248]
With add-on beta channel removal on 2/22/2018, it would be more than useful to have a way to automate add-on signing for beta versions to be hosted on the developer site.
This implies being able to upload unlisted add-ons and this does not seem to be possible for now with the current sign-addon module.
Reference: [web-ext issue 877](https://github.com/mozilla/web-ext/issues/877#issuecomment-289139651)

**Comment by kumar303** [comment]
Since `sign-addon` already handles signing unlisted add-ons, I think what you mean is to sign a new version of a *listed* add-on in an *unlisted* channel. Correct me if I'm wrong.

**Comment by mi-g** [comment]
You are correct, this is what i mean: with a public version of an add-on published on amo, being able to sign a beta version of this add-on for distribution on the developer site.

**Comment by kumar303** [comment]
This has been released in 0.3.0 https://github.com/mozilla/sign-addon/releases/tag/0.3.0

Thanks again, @welwood08 !
