### ISSUE TITLE
Add Greenkeeper or renovate?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/sign-addon#255]
Not sure how active this project is, but it may be worth trying to integrate [greenkeeper](https://greenkeeper.io/) or [renovate](https://renovatebot.com/) (the latter allows you to schedule updates to a certain day/time, which makes it a bit less noisy).

Newer versions of npm (**npm@6** or **npm@5.10**) have a new <kbd>$ npm audit</kbd> command which is similar to the old [**nsp**](http://npm.im/nsp) module, which detects potential vulnerable modules. You can sort of hack an audit right meow by using **npx** [if you're using npm@5.2+], like so:

```sh
$ git clone https://github.com/mozilla/sign-addon.git && cd sign-addon
$ npm install
$ npx npm@6 audit
...
[!] 32 vulnerabilities found - Packages audited: 7381 (7261 dev, 222 optional)
    Severity: 13 Low | 17 Moderate | 2 Critical
```

And to get a list of all current outdated modules, we can use good ol' <kbd>$ npm outdated</kbd>:

```sh
$ npm outdated

Package              Current  Wanted  Latest  Location
babel-polyfill         6.9.1  6.16.0  6.26.0  sign-addon
es6-error              3.0.1   4.0.0   4.1.1  sign-addon
es6-promisify          4.1.0   5.0.0   6.0.0  sign-addon
jsonwebtoken           7.1.7   7.1.9   8.2.1  sign-addon
mz                     2.4.0   2.5.0   2.7.0  sign-addon
request               2.74.0  2.79.0  2.86.0  sign-addon
source-map-support     0.4.2   0.4.6   0.5.6  sign-addon
chai                   3.5.0   3.5.0   4.1.2  sign-addon
grunt                  1.0.1   1.0.1   1.0.2  sign-addon
grunt-contrib-clean    1.0.0   1.0.0   1.1.0  sign-addon
grunt-contrib-watch    1.0.0   1.0.0   1.1.0  sign-addon
grunt-eslint          19.0.0  19.0.0  20.1.0  sign-addon
grunt-newer            1.2.0   1.2.0   1.3.0  sign-addon
when                   3.7.7   3.7.7   3.7.8  sign-addon
```

**Comment by muffinresearch** [comment]
@pdehaan Thanks for the heads-up - github admins have enabled the greenkeeper integration for this repo.

**Comment by muffinresearch** [comment]
Renovate is now up and running.
