### ISSUE TITLE
Add a function to extract the add-on id & version from the xpi

### ISSUE THREAD

**Issue by Standard8** [mozilla/sign-addon#27]
Looking at using this for uploading an xpi, I need to extract the id and version from the xpi.

It would be more convenient if we could move some of the functions from https://github.com/mozilla-jetpack/jpm/blob/1.0.7/lib/utils.js so that we could have it all in one package, rather than needing two packages.

**Comment by kumar303** [comment]
For sure! This was in the back of my mind but I hadn't filed an issue yet. It should be pretty straight forward to extract from jpm, it will just take some fiddling to pluck out all the RDF parts.
