### ISSUE TITLE
Use a consistent naming format for test files (spec or...)

### ISSUE THREAD

**Issue by kumar303** [mozilla/sign-addon#351]
I see that [PseudoProgress.spec.js](https://github.com/mozilla/sign-addon/blob/master/tests/PseudoProgress.spec.js) crept in which means we have a `*.spec` file mixed with `test.*` files. We should pick one naming format and make it consistent.

**Comment by willdurand** [comment]
Haha, I did not even realize... That will be fixed by #334 (hint: we'll use `.spec`)
