### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by willdurand** [mozilla/sign-addon#368]
We should release a new version of this lib. Given all the recent changes, it will likely be a new major version. Here is the current changelog:

```
77dc385 refactor: rewrite test suite with Jest (#364)
01fc2b3 chore: rename test files (#362)
c504b95 refactor: wait for validation & signing separately (#323)
940b77d Setup codecov (#354)
82b6789 Move noEmit into tsconfig (#355)
54c26bd refactor: Move mock classes to tests/helpers.js (#347)
ea9e747 Update README (#341)
82ad42b feat: drop node 8 support, start adding async/await, split source files (#342)
98c185a feat: Add types to one test file (#336)
```

...and a bunch of dependency updates.

**Comment by willdurand** [comment]
@kumar303 @diox WDYT? Major or minor release?

**Comment by kumar303** [comment]
It follows [semver](https://semver.org/) so it should be a major release but only because it drops Node 8 support, which is a breaking change. I suggest highlighting this in bold (or something) as a breaking change.

**Comment by willdurand** [comment]
Ok, that's what I had in mind too. I created a GitHub milestone to track what needs to be done before we can release it.
