### ISSUE TITLE
Source code submission

### ISSUE THREAD

**Issue by shaypeleg1** [mozilla/sign-addon#409]
As part of the AMO review process, some extensions are required to supply the source code in a zip file.
https://extensionworkshop.com/documentation/publish/source-code-submission/

Please add the option to submit the source code.

**Comment by ardittisrc** [comment]
+1
Since the recent changes in the AMO review process, we are not able able to use this library as part of our signing system.

**Comment by willdurand** [comment]
Yep, that sounds like a good idea.

**Comment by stoically** [comment]
Related: https://github.com/mozilla/addons-server/issues/9913

**Comment by pudgeball** [comment]
Heya :wave:  This is labeled as `blocked by upstream` but I think both upstream issues have been closed.  Is there a way to get source code submission into the queue of work?  It'd be amazing to be able to submit extensions via the API that require source code

**Comment by hyzyla** [comment]
Hello, everyone 👋  [Made](https://github.com/mozilla/sign-addon/pull/1038) a small contribution toward resolving this issue. Corresponding change also should be done on web-ext side: build archive and pass as argument to `sign` function of this library

**Comment by willdurand** [comment]
The unstable API now exposes an endpoint to submit sources:https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#version-sources
