### ISSUE TITLE
Update message for "signing took too long to complete" error 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/sign-addon#880]
If a developer submits a version for signing using web-ext and their version is selected for manual review, they see an error message that says "Signing took too long to complete; etc". 

We should give them more insight into what's going on. :) It would be good to update the message to something like, "Signing is pending, please check your add-on's status at https://addons.mozilla.org/developers/ to see if it has been selected for manual review." 

(Note, this needs a fact check -- and I'm open to edits/suggestions.)

// cc @wagnerand

**Comment by wagnerand** [comment]
Can we use something more general like:

"Signing is still pending, please check the status at addons.mozilla.org/developers later."

**Comment by willdurand** [comment]
> Can we use something more general like:
> 
> "Signing is still pending, please check the status at addons.mozilla.org/developers later."

+1

**Comment by caitmuenster** [comment]
What's a good time frame to suggest for later?

**Comment by willdurand** [comment]
Technically, it could be any time after the user reads the message. Maybe we could remove "later" and point users to the DevHub.

**Comment by wagnerand** [comment]
We could remove "later". The intent for having that was to try and avoid a developer going to devhub right away, which wouldn't be helpful since nothing would have happened to the status in a short time-frame.

**Comment by wagnerand** [comment]
Maybe it would be better to say something like:

"Signing is still pending, you will receive an email once there is an update on the status."

Thinking of it, asking devs to go to the devhub is of limited use anyway. All they would see that the add-on is still pending, without further info. And indicating this pull-behavior where the developer has to proactively check for update recurringly, we should refer to the push-behavior where AMO sends an email when there is an update on the status.

**Comment by caitmuenster** [comment]
LGTM, thanks @theone. Can we include "you will receive an email from nobody[@]mozilla[dot]org once there is a status update..." so they know what to look for?

**Comment by willdurand** [comment]
> LGTM, thanks @theone. Can we include "you will receive an email from nobody[@]mozilla[dot]org once there is a status update..." so they know what to look for?

s/theone/@wagnerand

Is the email address really useful, though?

**Comment by wagnerand** [comment]
Not sure if the address is useful and even more unclear if it's really used in all cases, for example some of the emails I get come from notifications@addons.mozilla.org via email-od.com. It might also depend on which email it is (e.g. triggered by a review vs auto-approval vs signing delay).

**Comment by caitmuenster** [comment]
Hm, maybe not. But sometimes that email gets filtered into a Spam folder and I'd like to encourage people to look for it before reaching out to us.

**Comment by willdurand** [comment]
Can we agree on a final copy please?

**Comment by willdurand** [comment]
Final copy is:

> Signing is still pending, you will receive an email once there is an update on the status of your submission. If you don’t see the email within 24 hours, please check your Spam folder.
