### ISSUE TITLE
Add a command line script

### ISSUE THREAD

**Issue by kumar303** [mozilla/sign-addon#9]
Currently, `signAddon()` can only be used programmatically. We should add a simple command line script, maybe with [yargs](http://yargs.js.org/).

**Comment by willdurand** [comment]
Do we still need this given that `web-ext` already provides a CLI?

**Comment by kumar303** [comment]
I think the original goal was to provide folks with a very lightweight CLI, where they wouldn't have to use `web-ext` and all its dependencies. However, that's not very compelling so I'd be fine to close this if you agree.

**Comment by willdurand** [comment]
Yeah, I agree. The code snippet in the README is probably enough (that's what I have been using so far).
