### ISSUE TITLE
Use `got` instead of `request`

### ISSUE THREAD

**Issue by willdurand** [mozilla/sign-addon#933]
This would fix https://github.com/mozilla/sign-addon/issues/932

**Comment by willdurand** [comment]
We cannot use `node-fetch` because it does not have any `proxy` feature and we need that kind of feature.

**Comment by asamuzaK** [comment]
FYI, you can do it with `node-fetch` + `https-proxy-agent`.

```
import HttpsProxyAgent from 'https-proxy-agent';
import fetch from 'node-fetch';
import process from 'process';

const fetchUrl = async url => {
  const proxy = process.env.HTTPS_PROXY || process.env.https_proxy ||
                process.env.HTTP_PROXY || process.env.http_proxy;
  const result = await fetch(url, {
    agent: proxy ? new HttpsProxyAgent(proxy) : null
  });
  return result;
};
```

**Comment by JoshuaKGoldberg** [comment]
👋 just checking in @willdurand, I'm not clear on the status of this issue and #932. Does this being assigned to you mean you're planning on sending a PR to resolve (and if so, is that still something you think you'll have time for)? Alternately, would you accept a PR from an external contributor like me?

**Comment by willdurand** [comment]
Our plan is to fully get rid of `sign-addon` in `web-ext` v8 (we are currently at v7). We considered updating this library with `node-fetch` or `got` or something else but the cost of maintaining two implementations[^1] is getting too high.

[^1]: sign-addon and the code for the submission API in web-ext
