### ISSUE TITLE
sign error - Missing "upload" key in multipart file data

### ISSUE THREAD

**Issue by arieljannai** [mozilla/sign-addon#94]
This is the error I receive:
`Server response: Missing "upload" key in multipart file data. ( status: 400 )`

I believe my xpi is good, since it's the same I'm sending to jpm. Any idea or something else I can try?

_currently I'm calling jpm from the code for the signing process, it would be nicer for my app to use that module instead so now I'm trying this separated module._

**Comment by kumar303** [comment]
Hmm, you could check the value of `xpiPath` when calling `signAddon()` but it should throw an error if it's empty or an unreadable path. Can you paste the output of `signAddon({verbose: true, ...})` ?

**Comment by arieljannai** [comment]
sure, I'll give it a try in a few days and I'll report.
about the xpiPath - I've checked it while debugging and the file did exist (also tried to use regular slashes and backslashes in the path)

**Comment by kumar303** [comment]
This doesn't sound like a valid bug to me. There's not enough info to diagnose it further so I'm closing it for now.

**Comment by arieljannai** [comment]
ok, sorry, I didn't had time to deep into it since I had to move to other projects
